stages:
  preprocess:
    cmd: python src/data/make_dataset.py data/raw data/processed
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/processed
  features:
    cmd: python src/features/build_features.py
    deps:
    - data/processed
    - src/features/build_features.py
    outs:
    - data/features
  train:
    cmd: python src/models/train_model.py
    deps:
    - data/features
    - src/models/train_model.py
    params:
    - train.max_iter
    outs:
    - models
    metrics:
    - metrics.json:
        cache: false
